#!/usr/bin/env bash
# more conditional statement if, elif, else

index=1
while [ $index -le 10 ]
do
	if [ $index -eq 4 ]
	then
		echo "bad luck"
		
	elif [ $index -eq 8 ]
	then
		echo "good luck"
	
	else
		echo "Best School"
	fi
	(( index++ ))
done
